import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Load the Poppins font with desired weights and subsets
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Cozy Corner | Your Happy Place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
